# Generated by Django 4.0.4 on 2022-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
